### ISSUE TITLE
US1 - Get all FoodSpots

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#1]
## Value Proposition

**As a User** 
**I want to see all my FoodSpots** 
**so that I can have an overview of all my favorite FoodSpots**
​

## Description

Cards for FoodSpots
<img width="172" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/7e42042e-0aec-40f2-9dac-4b0b0c17c52e">

## Acceptance Criteria

- [x] Cards for every Restaurant are shown
      ​

## Tasks

- [x] Create backend with controller, service, mongoDB-interface, model, unit and integration tests
- [x] Create frontend according to wireframes
      ​

## Complexity

M
