### ISSUE TITLE
User Login/Logout

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#11]
## Value Proposition

**As a User**
**I want to have an account on the website** 
**so that I can have my own foodspots** 
​

## Description
#LoginPage
<img width="239" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/dd1655bd-8977-49f3-9d6b-0d1d76aed6a1">

#SignUpPage
<img width="239" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/039cf3e0-2279-49dc-8367-5b346ef7ce45">
​

## Acceptance Criteria

- [x] LoginPage gets displays at first
- [x] Logout Button
      ​

## Tasks

- [x] Controller, Service and Class for User
- [x] Authenticated Paths creation in frontend
- [x] Login, Logout in frontend
      ​

## Complexity

L
