### ISSUE TITLE
US6 - User Registration

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#13]
## Value Proposition

**As a User**
**I want to have my own account** 
**so that I can have my own foodspots saved for myself** 
​

## Description
#LoginPage
<img width="239" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/dd1655bd-8977-49f3-9d6b-0d1d76aed6a1">

#SignUpPage
<img width="239" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/039cf3e0-2279-49dc-8367-5b346ef7ce45">
​

## Acceptance Criteria

- [ ] LoginPage gets displayed at first
- [ ] Text indicating where to click for registration
- [ ] Sign-up button
      ​

## Tasks

- [ ] Controller, Service Methods for signup
- [ ] permitAll path for sign-up
      ​

## Complexity

S
