### ISSUE TITLE
US7 - User/FoodSpot Validation and Exception Handling

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#14]
## Value Proposition

**As a User**
**I want to see if my account details or foodspots are right or missing something** 
**so that I can be notified beforehand** 
​

## Description
#SignupPage
<img width="234" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/63785325-e845-425a-96d0-65ed61f8b38a">

#Add FoodSpot Form
<img width="231" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/5a65ed25-2df3-48ef-b827-f3d9167a5c80">
​

## Acceptance Criteria

- [x] Not checked requirements are displayed for the user
- [x] In red text
- [x] Will disappear if checked/passed
      ​

## Tasks

- [x] Adapt backend with validation
- [x] Write new integration tests and exceptions for validation
- [x] frontend validation within the forms
      ​

## Complexity

M
