### ISSUE TITLE
US8 - Users own FoodSpots

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#17]
## Value Proposition

**As a User**
**I want to have my own FoodSpots**
**so that I can keep track of my own FoodSpots and keep them for myself**
​

## Acceptance Criteria

- [x] Added FoodSpots are shown within the categories
- [x] FoodSpots are only available for the user whom created them
      ​

## Tasks

- [x] Adapt FoodSpot Controller to save within the User
- [x] Expand FoodSpot Model with ENUM for PriceLevel
      ​

## Complexity

M
