### ISSUE TITLE
US2 - Add own FoodSpots

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#2]
## Value Proposition

**As a User**
**I want to add my own FoodSpots**
**so that I can keep track of favorites**
​

## Description
Add Button on the bottom right from overview
<img width="215" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/a4ea6856-ec48-4965-99cb-f3aab59a42ed">

Leads to this form for manually adding a FoodSpot
<img width="226" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/07247f6c-db6a-4da1-8a0e-e28ba46a283f">

## Acceptance Criteria

- [x] Button for adding a FoodSpot in HomePage
- [x] Form like in wireframes
      ​

## Tasks

- [x] Create backend with controller endpoint, service methods, model, unit and integration tests
- [x] Create frontend according to wireframes
      ​
## Complexity

M
