### ISSUE TITLE
US9 - Address Autocomplete and Maps-View

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#20]
## Value Proposition

**As a user**
**I want to have address suggestion and a view of all addresses of a category in a map**
**so that I can save sometime typing in the form and have a better overview place and distance-wise of all spots**
​

## Description
#Autocomplete Feature
<img width="226" alt="Bildschirmfoto 2023-08-07 um 09 21 41" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/d0e2b1a7-6297-45b5-b681-43e740e64946">
​
#Map-View
<img width="349" alt="Bildschirmfoto 2023-08-07 um 09 21 33" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/48982a62-1583-4cd2-bcbf-efcdd4268416">

## Acceptance Criteria

- [x] When typing in a address the input should be accompanied by address suggestions
- [x] Selecting one inserts the desired address inside the input 
- [x] Works for add foodspot form and for the edit mode of a existing foodspot
- [x] Within each category there should be a tab which displays either the list or the map view
- [x] Toggling the tabs reveals the respective view
      ​

## Tasks

- [x] Look for a Google Autocomplete Feature
- [x] Also a library for the tab feature
- [x] Map-view with markers for each foodspot category item
      ​

## Complexity

L
