### ISSUE TITLE
US10 - Menu with Account Page

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#22]
## Value Proposition

**As a User**
**I want to have a menu**
**so that I can access the website categorically. I can go to the Foodspots, to the fomr for adding a FoodSpot and my Account Page**
​

## Description

#Burger Menu
<img width="242" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/bbb4666e-690c-4261-beb4-7ebde03acce7">

#Menu opened
<img width="243" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/70ad1d46-b9de-452c-97c4-3f30c6003e59">

#Account Page
<img width="247" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/79009a31-602f-470f-9254-ec1d603cb37b">

## Acceptance Criteria

- [x] A burger menu is visible at the top of the home page
- [x] Clicking it reveals all possible navigation/site options
- [x] Should include Home, a map of all foodspots associated with the user account, a site to add a foodspot and a ccount page
- [x] Clicking a options leads you to the site
- [x] User Account Page lists user details, and a default profile picture which is changeable 
- [x] Logout button in account page      ​

## Tasks

- [x] React library for burger menu 
- [x] implement overlay for opening menu
- [x] New link routing
- [x] Account Page with DiceBear API      ​

## Complexity

XL
