### ISSUE TITLE
US11 - Reverse Geolocation & Add Categories

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#25]
## Value Proposition

**As a user**
**I want to insert my current address into the form and add own categories**
**so that I can quickly add a spot where I'm currently at and have specific categories**
​

## Description

#Add Categories
<img width="263" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/625542ec-decd-477a-afef-8861e4b8ebd7">

#Reverse Geolocation to get current position of user
<img width="297" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/f92a9166-3f63-43c2-bc60-e412bf0011c4">

## Acceptance Criteria

- [ ] On the HomePage it's clearly visible where to add a category
- [ ] Adding categories also gives option for uploading two pictures. A BG and one for the display
- [ ] In the Address fields within the app there is a button inside the form which indicates that pressing the button inserts your current address
- [ ] Every site has your account picture
      ​

## Tasks

- [ ] Create Backend for new categories
- [ ] Use Cloudinary for uploading images
- [ ] Use WebClient for Reverse Geolocation with Google API
- [ ] Create Frontend for these features
      ​

## Complexity

XL
