### ISSUE TITLE
US12 - Add Categories

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#29]
## Value Proposition

**As a user**
**I want to add my own categories**
**so that I have a more personal feeling with my account and I'm not dependend of already existing categories. Also unneeded categories aren't shown.**
​
## Description
#Add Button/Container for categories
<img width="331" alt="Bildschirmfoto 2023-08-18 um 18 47 39" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/336100e5-7e75-4fd2-bbe8-d80bf895526e">

#Form for add categorie request
<img width="335" alt="Bildschirmfoto 2023-08-18 um 18 47 49" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/2093e010-a7ab-4572-b998-a6bcfdd70db4">

#Preview for deciding the position in both views (HomePage and FoodSpotCard)
<img width="334" alt="Bildschirmfoto 2023-08-18 um 18 47 57" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/ff06fa83-7e42-446a-bf59-400fb857171c">

## Acceptance Criteria

- [x] A obvious and visible option for the user to add a categorie
- [x] Clicking it leads to a form
- [x] After completing the form I get a preview screen
- [x] Here I can position the images which I uploaded in the form
- [x] After that I can add a foodspot to my new category which should now appear on the homepage
      ​

## Tasks

- [x] UserModel gets a update with a list of categories
- [x] Write in the FoodSpot Controller new endpoint, service etc.
- [x] Two new endpoints:
- [x] One adds new categories to the list of the user and another one gets the current categories of the user
- [x] Frontend HomePage container which leads to a page with form. This form leads to a new preview.
      ​

## Complexity

XXL
