### ISSUE TITLE
US3 - Update FoodSpot

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#3]
## Value Proposition

**As a User** 
**I want to update FoodSpots** 
**so that I can fix my mistakes** 
​

## Description
Button for editing / entering edit-mode
<img width="207" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/f7830970-7a74-4dba-b1ed-f70ea67fb607">

Form for update
<img width="203" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/2412faf5-7261-4da5-80aa-4372992a5022">

## Acceptance Criteria

- [x] Button on FoodSpots to edit them
- [x] When clicked leads to a form for updating the FoodSpot
      ​

## Tasks

- [x] Create backend with controller endpoint, service methods, model, unit and integration tests
- [x] Create frontend according to wireframes
      ​

## Complexity

L
