### ISSUE TITLE
US4 - Delete FoodSpots

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-project-fullstack#4]
## Value Proposition

**As a User**
**I want to delete FoodSpots**
**so that I can keep my favorite FoodSpots up to date** 
​

## Description

Additional Button for deleting FoodSpot
<img width="202" alt="image" src="https://github.com/sahedw/capstone-project-fullstack/assets/122886715/d664fd8d-6cbb-4e50-873e-751f7f51882a">
​

## Acceptance Criteria

- [x] Button in Edit-Form to delete FoodSpot
- [x] After clicking FoodSpot is no longer available 
      ​

## Tasks

- [x] Create backend with controller endpoint, service methods, model, unit and integration tests
- [x] Create frontend according to wireframes
      
      ​

## Complexity

M
